# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='artist_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='tracks.Artists'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='album_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='tracks.Albums'),
        ),
    ]
